name = "mobilmax-bazar-api"
main = "worker.js"
compatibility_date = "2026-08-31"

[vars]
GITHUB_BRANCH = "main"
GITHUB_OWNER = "JarekZones"
GITHUB_REPO = "Bazar"
TELEGRAM_CHAT_ID = "8845070220"

[[kv_namespaces]]
binding = "IMEI_KV"
id = "7c9893ad46654d869454d3c09fe0b85b"
